[package]
name = "covidreport"
version = "0.1.0"
authors = ["dga"]
edition = "2021"

[dependencies]
anyhow = "*"
csv = "*"
serde = { version="*", features = ["derive"] }
itertools = "*"
plotters = "*"
chrono = { version="*", features = ["serde"] }
structopt = "*"
palette = "*"
